inputs:
  port:
    description: 'Port for app'
    default: 7001
  environment:
    description: 'Env name for var'
    default: 'Dev'
runs:
  using: "composite"
  steps: 
    - name: Checkout repository
      uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/python-greetings'
        path: 'python-greetings'
        ref: 4e911440a9886c7c26ccbb4eb55f0bc2a5067b51
        fetch-depth: 0       
      

